### ISSUE TITLE
LFMC Scenario B.ipynb

### ISSUE THREAD

**Issue by qt111111** [lynn-miller/LFMC_from_MODIS#1]
when I ran “LFMC Scenario B.ipynb”，a error happened,i don't know why,can you help me?thanks
![image](https://user-images.githubusercontent.com/56248051/120095411-73433800-c158-11eb-9cd3-13a39616ee8b.png)
![image](https://user-images.githubusercontent.com/56248051/120095428-835b1780-c158-11eb-97ab-2700e02d932a.png)

**Comment by lynn-miller** [comment]
One reason this could happen is if you have non-numeric data in the "Land Cover" column in your sample dataset. The Globe-LFMC dataset I used has numeric landcover classes, so the code assumes this. The code that does the stratified splitting groups any land cover classes that are too small to split individually into one class which is given the value 0 (number zero). If some/all the other land cover class values are not numeric, the sklearn splitter will then fail with the error you got. Please check and let me know if this is your problem.

**Comment by qt111111** [comment]
> One reason this could happen is if you have non-numeric data in the "Land Cover" column in your sample dataset. The Globe-LFMC dataset I used has numeric landcover classes, so the code assumes this. The code that does the stratified splitting groups any land cover classes that are too small to split individually into one class which is given the value 0 (number zero). If some/all the other land cover class values are not numeric, the sklearn splitter will then fail with the error you got. Please check and let me know if this is your problem.

yes, "Land Cover" column in "sample.csv" are "shrubland","Tree cover",etc.What should I do?




<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///D:/Temp/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///D:/Temp/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





Shrubland
--
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Shrubland
Tree cover, needleleaved, evergreen,   closed to open (&gt;15%)

**Comment by lynn-miller** [comment]
The easiest way to fix this is in model_utils.py change line 24 as follows:
current code: `sites.loc[sites.stratify.isin(lc), 'stratify'] = 0`
new code: `sites.loc[sites.stratify.isin(lc), 'stratify'] = '0'`

I'll work on a fix to the code that handles either numeric or character format. This should work in the mean time.

**Comment by qt111111** [comment]
> The easiest way to fix this is in model_utils.py change line 24 as follows:
> current code: `sites.loc[sites.stratify.isin(lc), 'stratify'] = 0`
> new code: `sites.loc[sites.stratify.isin(lc), 'stratify'] = '0'`
> 
> I'll work on a fix to the code that handles either numeric or character format. This should work in the mean time.

thank you very much，I successfully run the code. What is the principle of '0'，what is the difference between 0 and '0'

**Comment by lynn-miller** [comment]
That line of code is where the small landcover groups are merged into a single group. The original code sets the value of that group to the number 0, so works if the other landcover values are also numeric. The changed code sets it to the character '0', so works if the other landcover values are character strings.

**Comment by qt111111** [comment]
> That line of code is where the small landcover groups are merged into a single group. The original code sets the value of that group to the number 0, so works if the other landcover values are also numeric. The changed code sets it to the character '0', so works if the other landcover values are character strings.

Thank you. I see that there are some other programs that combine remote sensing images, such as landsat-8, to predict LFMC.  Next, I will try to combine the image data for experiments.

**Comment by qt111111** [comment]
By the way,I haven't found the paper "Live fuel moisture content estimation from MODIS: a deep learning approach" mentioned in readme.md. Is it not published yet?

**Comment by lynn-miller** [comment]
No, it's currently under review.

I've just uploaded the fix for this issue - it's essentially the work around I gave you, but expanded to cope with either numeric or character values for Land Cover.

**Comment by qt111111** [comment]
> No, it's currently under review.
> 
> I've just uploaded the fix for this issue - it's essentially the work around I gave you, but expanded to cope with either numeric or character values for Land Cover.

Good luck and hope to see your paper as soon as possible

**Comment by lynn-miller** [comment]
Thank you!
